
// list of topics a CSCS might be an expert on
const topicArray = [
    "Benefits of High-Intensity Interval Training (HIIT)",
    "Nutrition Strategies for Muscle Gain",
    "Incorporating Flexibility Training into Your Routine",
    "Understanding Macronutrients: Carbohydrates, Proteins, and Fats",
    "The Importance of Proper Hydration for Performance",
    "Functional Training for Everyday Movement",
    "How to Prevent and Manage Exercise-Induced Injuries",
    "Optimizing Recovery: Sleep, Nutrition, and Rest Days",
    "The Role of Supplements in Fitness and Performance",
    "Mindfulness and Stress Management Techniques",
    "Building a Home Gym on a Budget",
    "The Science Behind Weightlifting: Muscles and Mechanics",
    "Improving Athletic Performance with Plyometric Training",
    "Understanding Body Composition: Muscle vs. Fat",
    "Creating Healthy Habits for Long-Term Success",
    "The Benefits of Outdoor Exercise and Nature Therapy",
    "Navigating Nutrition Labels and Making Informed Choices",
    "Cardiovascular Exercise: Beyond Just Running",
    "The Psychology of Motivation and Goal Setting",
    "Mastering the Basics: Squats, Deadlifts, and Bench Press",
    "Meal Prep and Planning for Busy Lifestyles",
    "Injury Rehabilitation and Return to Activity Protocols",
    "The Role of Genetics in Fitness and Performance",
    "Functional Foods: Nutrient-Dense Choices for Optimal Health",
    "Interval Training for Fat Loss and Endurance",
    "Mind-Body Connection: Yoga and Meditation",
    "Understanding Resting Metabolic Rate and Energy Balance",
    "Ergogenic Aids: Supplements for Performance Enhancement",
    "Balancing Fitness and Family: Tips for Busy Parents",
    "The Science of Stretching: Static vs. Dynamic Techniques",
    "Pre- and Post-Workout Nutrition Guidelines",
    "Incorporating Resistance Bands for Strength and Stability",
    "The Importance of Periodization in Training Programs",
    "Hybrid Training: Combining Different Modalities for Results",
    "Gut Health and Its Impact on Overall Well-Being",
    "Functional Movement Screening for Injury Prevention",
    "The Role of Electrolytes in Hydration and Performance",
    "Navigating Fitness Plateaus: Strategies for Progress",
    "Exercise Prescription for Special Populations",
    "The Power of Positive Thinking: Mental Toughness in Training",
    "Maximizing Performance Through Proper Warm-Up and Cool Down",
    "Understanding Delayed Onset Muscle Soreness (DOMS)",
    "Healthy Eating on a Budget: Tips and Tricks",
    "Social Support and Accountability in Fitness Journey",
    "The Science of Sleep: Optimizing Rest and Recovery",
    "Cross-Training for Overall Fitness and Injury Prevention",
    "The Role of Hormones in Exercise and Body Composition",
    "Core Training Beyond Crunches: Functional Movements",
    "Managing Weight During Menopause and Hormonal Changes",
    "Adapting Workouts for Travel and Time Constraints",
    "Injury Prevention Strategies for Runners and Endurance Athletes",
    "Effective Communication with Fitness Professionals",
    "Understanding Metabolism: Myths vs. Facts",
    "The Benefits of Group Exercise Classes",
    "Creating a Positive Body Image and Self-Confidence",
    "Supplementing for Vegan and Vegetarian Athletes",
    "Training Through Pregnancy: Guidelines and Considerations",
    "Sports Nutrition for Peak Performance",
    "Circuit Training for Total-Body Conditioning",
    "The Role of Mindfulness in Eating Behavior",
    "Functional Anatomy: Understanding Joint Actions and Muscles",
    "Incorporating Balance and Stability Training into Workouts",
    "Postural Assessment and Correction for Improved Performance",
    "Nutrient Timing for Optimal Performance and Recovery",
    "Debunking Fitness Myths: Separating Fact from Fiction",
    "The Importance of Cross-Training for Injury Prevention",
    "Strategies for Overcoming Exercise Plateaus",
    "Effective Goal Setting for Sustainable Fitness Progress",
    "Incorporating Strength Training for Older Adults",
    "The Benefits of Resistance Training for Women",
    "Navigating Dietary Supplements: Safety and Efficacy",
    "Functional Movement Patterns for Everyday Life",
    "Training Strategies for Enhancing Endurance",
    "The Role of Dopamine and Exercise Addiction",
    "Injury Prevention Techniques for Contact Sports",
    "The Science of Fat Loss: Calories In vs. Calories Out",
    "Nutrition Strategies for Pre- and Post-Competition",
    "Hydration Strategies for Hot and Humid Environments",
    "Understanding Heart Rate Zones for Effective Cardio",
    "The Psychology of Habit Formation and Behavior Change",
    "Recovery Techniques for Muscle Soreness and Fatigue",
    "Exercise and Mental Health: Managing Stress and Anxiety",
    "Functional Training for Older Adults: Maintaining Independence",
    "Eating Disorders in Athletes: Detection and Prevention",
    "The Benefits of Outdoor Recreation for Physical and Mental Health",
    "The Role of Cortisol in Stress and Weight Management",
    "Optimizing Performance Through Nutrient Timing",
    "Interval Training for Improved VO2 Max and Anaerobic Capacity",
    "The Impact of Alcohol Consumption on Fitness and Health",
    "Mindful Eating: Cultivating Awareness and Satisfaction",
    "Preventing and Managing Overtraining Syndrome",
    "The Importance of Proper Footwear for Exercise",
    "Understanding Glycemic Index and Blood Sugar Regulation",
    "Incorporating Foam Rolling for Recovery and Mobility",
    "Navigating Dietary Restrictions While Maintaining Fitness Goals",
    "The Benefits of CrossFit and Functional Fitness Training",
    "The Role of the Nervous System in Muscle Contraction",
    "Healthy Snacking Options for On-the-Go Lifestyles",
    "The Science of Thermoregulation: Exercise in Extreme Temperatures",
    "Incorporating Mindfulness Practices into Daily Life",
    "The Role of Nutrition in Bone Health",
    "Injury Prevention Strategies for Weightlifters",
    "The Benefits of Resistance Bands for Rehabilitation",
    "Understanding Energy Systems: ATP-PC, Glycolytic, and Oxidative",
    "Functional Movement Patterns for Injury Prevention",
    "The Science of Muscle Hypertrophy: Growth Factors and Mechanisms",
    "Ergonomics in the Workplace: Improving Posture and Health",
    "Incorporating Kettlebell Training for Full-Body Workouts",
    "The Importance of Core Stability for Athletic Performance",
    "Nutrition Strategies for Endurance Events: Marathon, Triathlon, etc.",
    "The Role of Carbohydrates in Exercise Performance",
    "Preventing and Managing Shin Splints",
    "Developing Explosive Power: Plyometrics and Olympic Lifts",
    "The Benefits of Swimming for Cardiovascular Health",
    "Understanding Heart Rate Variability (HRV) and Recovery",
    "Mindful Eating for Weight Management and Health",
    "The Science of Muscle Memory: Training Adaptations and Retention",
    "The Importance of Proper Form and Technique in Exercise",
    "Interval Training for Weight Loss and Metabolic Health",
    "Injury Rehabilitation Techniques for Runners",
    "Nutrition Strategies for Youth Athletes",
    "The Benefits of Active Recovery Workouts",
    "Incorporating Yoga for Flexibility and Stress Relief",
    "Understanding Overtraining Syndrome: Signs and Symptoms",
    "The Role of Leucine in Muscle Protein Synthesis",
    "Balancing Cardio and Strength Training for Optimal Results",
    "The Science of Thermogenesis: Boosting Metabolism",
    "The Benefits of Functional Movement Assessments",
    "Training Strategies for Obstacle Course Racing (OCR)",
    "The Role of Magnesium in Exercise Performance and Recovery",
    "The Psychology of Injury Rehabilitation and Return to Sport",
    "Developing Speed and Agility for Sports Performance",
    "Optimizing Nutrition for Recovery Between Training Sessions",
    "The Benefits of Cross-Training for Overall Fitness",
    "Incorporating Balance Exercises for Fall Prevention",
    "The Science of Muscle Fiber Types: Fast-Twitch vs. Slow-Twitch",
    "Understanding DOMS: Causes, Prevention, and Treatment",
    "The Role of Myofascial Release in Injury Prevention",
    "The Importance of Consistency in Fitness and Nutrition",
    "Navigating Sports Drinks and Electrolyte Replacement",
    "The Benefits of High-Protein Diets for Muscle Building",
    "Incorporating Resistance Training for Older Adults",
    "The Psychology of Weight Loss: Mindset and Motivation",
    "Understanding EPOC (Excess Post-Exercise Oxygen Consumption)",
    "The Role of Omega-3 Fatty Acids in Inflammation and Recovery",
    "Hydration Strategies for Cold Weather Exercise",
    "Injury Prevention Techniques for CrossFit Athletes",
    "The Benefits of Functional Fitness for Daily Life",
    "Understanding Heat Illnesses and Prevention Strategies",
    "The Role of Creatine Supplementation in Performance",
    "The Science of Joint Health and Injury Prevention",
    "Incorporating Mobility Drills for Joint Health",
    "Optimizing Recovery Nutrition for Muscle Repair",
    "The Benefits of Prehabilitation Exercises",
    "Understanding the Female Athlete Triad",
    "Injury Prevention Techniques for Team Sports",
    "The Importance of Periodic Deloading in Training Programs",
    "The Benefits of Active Transportation: Walking, Biking, etc.",
    "The Science of BCAA (Branched-Chain Amino Acids) Supplementation",
    "Incorporating Bodyweight Exercises for Strength and Conditioning",
    "Understanding Cortisol: The Stress Hormone and Its Effects",
    "The Role of Vitamin D in Bone Health and Immunity",
    "The Benefits of Functional Strength Training for Seniors",
    "Injury Prevention Strategies for Cyclists",
    "The Science of Neuromuscular Adaptations to Training",
    "The Importance of Proper Breathing Techniques During Exercise",
    "Understanding Heat Acclimatization for Athletes",
    "Incorporating Meditation for Stress Reduction and Mental Clarity",
    "The Benefits of Circuit Training for Fat Loss",
    "Nutrition Strategies for Vegetarian and Vegan Athletes",
    "The Role of Sleep in Athletic Performance and Recovery",
    "Injury Prevention Techniques for Martial Arts Practitioners",
    "The Science of High-Intensity Weight Training",
    "Understanding the Glycemic Load of Foods",
    "The Benefits of Foam Rolling for Recovery and Flexibility",
    "Incorporating Functional Training for Golfers",
    "The Role of Antioxidants in Exercise Recovery",
    "Understanding Training Adaptations: SAID Principle",
    "The Benefits of Pilates for Core Strength and Stability",
    "Injury Prevention Techniques for Rock Climbers",
    "The Science of Blood Flow Restriction Training",
    "The Importance of Warm-Up and Cool-Down Protocols",
    "Understanding Hyponatremia: Causes and Prevention",
    "Incorporating Mindful Movement Practices for Well-Being",
    "The Benefits of Interval Training for Cardiorespiratory Fitness",
    "Nutrition Strategies for Powerlifting Competitions",
    "The Role of Inflammation in Exercise Recovery",
    "Injury Prevention Techniques for Tennis Players",
    "The Science of VO2 Max and Its Relationship to Endurance",
    "The Benefits of Barefoot Training for Foot Strength and Mobility",
    "Understanding Protein Synthesis and Muscle Repair",
    "Incorporating Agility Drills for Sports Performance",
    "The Role of Carbohydrate Loading for Endurance Events",
    "The Benefits of Outdoor CrossFit Workouts",
    "Understanding Metabolic Conditioning for Fat Loss",
    "Injury Prevention Techniques for Hikers",
    "The Science of Blood Sugar Regulation During Exercise",
    "The Importance of Proper Nutrition for Injury Recovery",
    "Incorporating Dynamic Stretching for Warm-Up",
    "The Benefits of Active Travel: Exploring on Foot or Bike",
    "Understanding Oxygen Consumption and Exercise Efficiency",
    "The Role of Glucose in Brain Function and Performance",
    "Understanding the Basics of Weight Loss: Calories In vs. Calories Out",
    "The Role of Nutrition in Weight Management",
    "Incorporating Portion Control for Weight Loss Success",
    "The Benefits of High-Fiber Foods for Weight Loss",
    "Understanding the Psychology of Eating for Weight Management",
    "The Role of Protein in Satiety and Weight Loss",
    "Creating a Sustainable Diet Plan for Long-Term Weight Loss",
    "The Science of Metabolism: Boosting Your Metabolic Rate",
    "Navigating Emotional Eating and Stress-Related Weight Gain",
    "Incorporating Mindful Eating Practices for Weight Loss",
    "Understanding the Importance of Hydration in Weight Management",
    "The Role of Sleep in Weight Loss and Appetite Regulation",
    "Incorporating Physical Activity for Weight Loss",
    "The Benefits of Strength Training for Weight Loss",
    "Understanding the Role of Hormones in Weight Regulation",
    "Incorporating Interval Training for Effective Fat Loss",
    "The Role of Meal Timing in Weight Management",
    "Understanding the Impact of Processed Foods on Weight Gain",
    "The Benefits of Meal Prep for Weight Loss Success",
    "Incorporating Low-Glycemic Index Foods for Stable Blood Sugar",
    "Understanding the Role of Gut Health in Weight Management",
    "The Science of Weight Plateaus: Breaking Through Sticking Points",
    "Incorporating Whole Foods for Nutrient Density and Weight Loss",
    "Understanding the Link Between Stress and Weight Gain",
    "The Role of Self-Compassion in Weight Loss Journeys",
    "Incorporating Intuitive Eating Principles for Weight Management",
    "The Benefits of Cooking at Home for Weight Loss",
    "Understanding the Role of Macronutrients in Weight Loss",
    "Incorporating Healthy Fats for Satiety and Weight Management",
    "The Science of Emotional Eating: Coping Strategies and Solutions",
    "Understanding the Impact of Sugar on Weight Gain and Health",
    "Incorporating Resistance Training for Metabolic Health",
    "The Benefits of Walking for Weight Loss and Cardiovascular Health",
    "Understanding the Role of Genetics in Weight Management",
    "Incorporating Stress Management Techniques for Weight Loss",
    "The Science of Thermodynamics and Weight Loss",
    "Navigating Social Situations and Eating Out While Dieting",
    "Understanding the Role of Insulin Resistance in Weight Gain",
    "Incorporating High-Volume, Low-Calorie Foods for Weight Loss",
    "The Benefits of Tracking Food Intake and Progress",
    "Understanding the Impact of Sleep Deprivation on Weight Gain",
    "Incorporating Plant-Based Proteins for Weight Loss",
    "The Role of Mindfulness in Breaking Unhealthy Eating Habits",
    "Understanding the Link Between Hormonal Imbalance and Weight Gain",
    "Incorporating Meditation for Stress Reduction and Weight Management",
    "The Benefits of Support Groups and Accountability Partnerships",
    "Understanding the Role of Leptin and Ghrelin in Appetite Regulation",
    "Incorporating HIIT Workouts for Maximum Caloric Burn",
    "The Science of Food Cravings: Causes and Strategies",
    "Understanding the Impact of Alcohol Consumption on Weight Loss",
    "Incorporating Strategies for Overcoming Plateaus in Weight Loss",
    "The Benefits of Setting Realistic and Achievable Goals",
    "Understanding the Psychology of Body Image and Self-Esteem",
    "Incorporating Behavioral Changes for Long-Term Weight Management",
    "The Role of Community and Social Support in Weight Loss",
    "Understanding the Impact of Chronic Stress on Weight Gain",
    "Incorporating Fiber-Rich Foods for Satiety and Weight Control",
    "The Benefits of Intermittent Fasting for Weight Loss",
    "Understanding the Connection Between Hormones and Hunger",
    "Incorporating Low-Calorie, Nutrient-Dense Foods for Weight Loss",
    "The Science of Binge Eating Disorder: Causes and Coping Strategies",
    "Understanding the Role of the Microbiome in Weight Management",
    "Incorporating Mindful Movement for Weight Loss and Stress Reduction",
    "The Benefits of Keeping a Food Journal for Accountability",
    "Understanding the Impact of Medications on Weight Gain",
    "Incorporating Self-Compassion and Positive Self-Talk in Weight Loss",
    "The Role of Cortisol in Belly Fat Accumulation",
    "Understanding the Importance of Consistency in Weight Loss Efforts",
    "Incorporating Cardiovascular Exercise for Weight Management",
    "The Benefits of Meal Timing and Frequency for Weight Loss",
    "Understanding the Role of Blood Sugar Regulation in Weight Management",
    "Incorporating Healthy Substitutions for High-Calorie Foods",
    "The Science of Appetite Control: Strategies for Managing Hunger",
    "Understanding the Link Between Depression and Weight Gain",
    "Incorporating Structured Meal Plans for Weight Loss Success",
    "The Benefits of Cooking Skills and Culinary Knowledge for Weight Management",
    "Understanding the Impact of Food Sensitivities on Weight Loss",
    "Incorporating Mindfulness-Based Stress Reduction for Weight Management",
    "The Role of Environmental Factors in Weight Gain",
    "Understanding the Connection Between Sleep Quality and Weight Loss",
    "Incorporating Hydration Strategies for Weight Management",
    "The Benefits of Reducing Added Sugars for Weight Loss",
    "Understanding the Role of Emotional Resilience in Weight Management",
    "Incorporating Strength-Based Approaches to Weight Loss",
    "The Science of Hormonal Birth Control and Weight Gain",
    "Understanding the Impact of Menopause on Weight Management",
    "Incorporating Gratitude Practices for Emotional Well-Being and Weight Loss",
    "The Benefits of Building a Healthy Relationship with Food for Weight Management",
    "Understanding the Role of Self-Regulation in Weight Loss",
    "Incorporating Mindful Eating for Improved Digestion and Weight Control",
    "The Science of Yo-Yo Dieting: Effects on Metabolism and Weight",
    "Understanding the Link Between Chronic Inflammation and Weight Gain",
    "Incorporating Resistance Bands for At-Home Workouts and Weight Loss",
    "The Benefits of Outdoor Activities for Weight Management",
    "Understanding the Impact of Social Media on Body Image and Weight Perception",
    "Incorporating Social Support Networks for Sustainable Weight Loss",
    "The Role of Cognitive Behavioral Therapy in Weight Management",
    "Understanding the Connection Between Childhood Trauma and Weight Gain",
    "Incorporating Self-Care Practices for Stress Reduction and Weight Management",
    "The Benefits of Balanced Meals and Snacks for Weight Loss",
    "Understanding the Impact of Sleep Apnea on Weight and Metabolism",
    "Incorporating Mindful Cooking for Healthier Meal Preparation",
    "The Role of Hormonal Imbalance in Weight Loss Resistance",
    "Understanding the Link Between Chronic Pain and Weight Gain",
    "Incorporating Resistance Training for Women and Weight Loss",
    "The Benefits of Mindful Movement Practices for Weight Management",
    "Understanding the Impact of Environmental Toxins on Weight",
    "Incorporating Cooking Classes and Culinary Education for Weight Management",
    "The Science of Stress Eating: Coping Mechanisms and Alternatives",
    "Understanding the Role of Gut Microbes in Weight Regulation",
    "Incorporating Gratitude Journals for Emotional Well-Being and Weight Loss",
    "The Benefits of Group Fitness Classes for Weight Management",
    "Understanding the Connection Between Gut Health and Weight Loss",
    "Incorporating Stress-Relief Techniques for Weight Management",
    "The Role of Emotional Intelligence in Weight Loss",
    "Understanding the Impact of Artificial Sweeteners on Weight and Health",
    "Incorporating Mindfulness-Based Interventions for Weight Management",
    "The Benefits of Nutrient Timing for Weight Loss and Muscle Gain",
    "Understanding the Link Between Sleep Disorders and Weight Gain",
    "Incorporating Family Support Systems for Successful Weight Management",
    "The Role of Self-Compassion in Overcoming Weight Loss Challenges",
    "Understanding the Impact of Chronic Inflammation on Weight",
    "Incorporating Healthy Coping Mechanisms for Stress-Induced Weight Gain",
    "The Benefits of Mindfulness Meditation for Emotional Eating",
    "Understanding the Connection Between Trauma and Weight Gain",
    "Incorporating Outdoor Exercise for Weight Loss and Mental Health",
    "The Role of Social Determinants of Health in Weight Management",
    "Understanding the Impact of Childhood Obesity on Adult Health",
    "Incorporating Mindfulness-Based Stress Reduction for Weight Loss",
    "The Benefits of Positive Affirmations for Weight Management",
    "Understanding the Link Between Insulin Resistance and Weight Gain",
    "Incorporating Nature Therapy for Stress Reduction and Weight Management",
    "The Role of Emotional Regulation in Successful Weight Loss",
    "Understanding the Connection Between Food Addiction and Weight Gain",
    "Incorporating Gratitude Practices for Weight Loss Motivation",
    "The Benefits of Animal-Assisted Therapy for Emotional Eating",
    "Understanding the Impact of Social Support on Weight Management",
    "Incorporating Mindful Walking for Weight Loss and Mental Health",
    "The Role of Sleep Hygiene in Weight Regulation",
    "Understanding the Connection Between Anxiety and Weight Gain",
    "Incorporating Mindfulness-Based Eating for Weight Management",
    "The Benefits of Art Therapy for Emotional Wellness and Weight Loss",
    "Understanding the Link Between Adverse Childhood Experiences and Weight",
    "Incorporating Breathwork for Stress Reduction and Weight Management",
    "The Role of Trauma-Informed Care in Weight Loss Programs",
    "Understanding the Impact of Body Image Distortion on Weight Perception",
    "Incorporating Dance Therapy for Weight Loss and Body Positivity",
    "The Benefits of Journaling for Emotional Processing and Weight Management",
    "Understanding the Connection Between Perfectionism and Weight Gain",
    "Incorporating Animal-Assisted Activities for Weight Management Support",
    "The Role of Community Gardens in Promoting Healthy Eating and Weight Loss",
    "Understanding the Impact of Environmental Stressors on Weight",
    "Incorporating Mindful Breathing Techniques for Stress Reduction and Weight Loss",
    "The Benefits of Equine-Assisted Therapy for Emotional Eating Patterns",
    "Understanding the Link Between Body Dysmorphia and Weight Obsession",
    "Incorporating Gardening for Physical Activity and Weight Management",
    "The Role of Social Prescribing in Addressing Emotional Eating Behaviors",
    "Understanding the Connection Between Loneliness and Weight Gain",
    "Incorporating Mindful Crafting for Stress Reduction and Weight Management",
    "The Benefits of Therapeutic Recreation for Emotional Resilience and Weight Loss",
    "Understanding the Impact of Environmental Pollution on Weight and Health",
    "Incorporating Expressive Arts Therapy for Body Image Healing and Weight Loss",
    "The Role of Community Supported Agriculture (CSA) in Healthy Eating and Weight Loss",
    "Understanding the Link Between Childhood Adversity and Adult Weight Struggles",
    "Incorporating Mindful Coloring for Stress Relief and Weight Management",
    "The Benefits of Ecotherapy for Emotional Well-Being and Sustainable Weight Loss",
    "Resistance training for women's weight loss",
    "High-intensity interval training (HIIT) for women",
    "Nutritional strategies for sustainable weight loss in women",
    "Role of strength training in improving women's metabolism",
    "Importance of protein intake for women's weight loss",
    "Balancing macronutrients for women's weight management",
    "Women-specific dietary considerations for fat loss",
        "Addressing hormonal factors in women's weight loss",
        "The impact of stress on women's weight and how to manage it",
        "Role of sleep in women's weight loss and overall health",
        "Strategies for women to overcome emotional eating habits",
        "Understanding and managing cravings in women's diets",
        "Building a supportive social environment for women's weight loss goals",
        "Body positivity and its role in women's weight loss journey",
        "Mindful eating techniques for women to support weight loss",
        "Incorporating mindfulness practices into women's lifestyle for weight management",
        "Gut health and its influence on women's weight loss efforts",
        "Strategies for healthy eating out for women on a weight loss journey",
        "Building a sustainable exercise routine for women's weight loss",
        "The role of cardio exercise in women's fat loss",
        "Effective ways to measure progress for women's weight loss goals",
        "Understanding metabolic rate variations among women and its impact on weight loss",
        "Interval training for women: Benefits and considerations",
        "Resistance training myths and facts for women's weight loss",
        "The importance of hydration in women's weight loss and overall health",
        "Pre- and post-workout nutrition strategies for women",
        "Combating plateaus in women's weight loss journey",
        "Managing menstrual cycle-related changes during weight loss in women",
        "Strategies for maintaining muscle mass during women's weight loss",
        "The role of supplements in supporting women's weight loss goals",
        "Addressing body image issues in women's weight loss programs",
        "Social and cultural factors influencing women's attitudes towards weight loss",
        "Women-specific dietary approaches for managing insulin resistance and weight loss",
        "Postpartum weight loss strategies for new mothers",
        "The impact of menopause on women's weight and metabolism",
        "Managing cravings and binge eating in women's weight loss programs",
        "Role of strength training in preventing muscle loss during weight loss in women",
        "The psychology of weight loss: Motivation, mindset, and behavior change for women",
        "Navigating challenges in women's weight loss maintenance",
        "Strategies for women to overcome barriers to exercise adherence",
        "Strategies for healthy meal prep and planning for women's weight loss",
        "Effective strategies for stress management in women's weight loss programs",
        "Understanding and addressing emotional triggers for overeating in women",
        "The role of self-care practices in supporting women's weight loss journey",
        "Hormonal changes during pregnancy and their impact on weight management",
        "The impact of breastfeeding on women's metabolism and weight loss",
        "Strategies for healthy snacking and portion control in women's diets",
        "Building a positive relationship with food for sustainable weight loss in women",
        "Understanding and managing thyroid issues in women's weight loss efforts",
        "The role of medical conditions like PCOS in women's weight loss challenges",
        "Strategies for managing fluid retention and bloating in women's weight loss",
        "The impact of alcohol consumption on women's weight loss goals",
        "Strategies for dining out while on a weight loss journey for women",
        "The importance of self-monitoring and accountability in women's weight loss programs",
        "The role of professional support (nutritionists, counselors, trainers) in women's weight loss",
        "Incorporating intuitive eating principles into women's weight loss strategies",
        "Strategies for maintaining weight loss and preventing regain in women",
        "Balancing fitness and family commitments for busy women on a weight loss journey",
        "Addressing body composition changes beyond weight loss in women",
        "Strategies for overcoming negative body image issues during weight loss in women",
        "The impact of sleep quality and quantity on women's weight loss efforts",
        "Practical tips for managing emotional stress eating in women's lives",
        "Building resilience and coping mechanisms for challenges encountered during weight loss",
        "Utilizing behavioral change techniques for sustainable weight loss in women",
        "Addressing the role of genetics in women's weight loss challenges",
        "The importance of community and support networks in women's weight loss programs",
        "Women-specific considerations in designing effective weight loss meal plans",
        "Incorporating flexibility and adaptability into women's weight loss strategies",
        "The role of cooking skills and meal preparation techniques in women's weight loss",
        "Strategies for managing and preventing injuries during exercise for women",
        "Understanding the impact of environmental factors on women's eating habits and weight",
        "The relationship between mindset and physical health in women's weight loss",
        "Techniques for stress reduction and relaxation to support women's weight loss",
        "Strategies for improving body composition and muscle tone in women",
        "The impact of aging on women's metabolism and weight management",
        "Strategies for balancing hormones naturally to support weight loss in women",
        "Understanding and overcoming self-sabotage patterns in women's weight loss",
        "Strategies for navigating social situations and peer pressure while on a weight loss journey",
        "The role of self-compassion and positive self-talk in women's weight loss efforts",
        "Overcoming perfectionism and unrealistic expectations in women's weight loss goals",
        "Strategies for managing time and energy to prioritize health and fitness for women",
        "Addressing common misconceptions and myths about women's weight loss",
        "The impact of chronic stress on women's weight and health",
        "Strategies for incorporating physical activity into daily life for busy women",
        "The importance of setting realistic and achievable goals in women's weight loss",
        "Celebrating non-scale victories and progress markers in women's weight loss journey",
        "Incorporating variety and enjoyment into exercise routines for women",
        "Understanding the role of sleep hygiene in supporting women's weight loss goals",
        "Strategies for breaking through weight loss plateaus in women",
        "The importance of self-care practices in women's overall well-being and weight loss",
        "Incorporating functional movement patterns into women's exercise routines for weight loss",
        "Understanding the impact of past traumas and experiences on women's relationship with food and weight",
        "Strategies for managing and preventing binge eating episodes in women's lives",
        "The role of empowerment and self-efficacy in sustaining long-term weight loss success for women"
    ]

    const systemPromptForGettingTitle = `As an expert in kinesiology, exercise science, and human nutrition, with a background as an NSCA CSCS, I specialize in simplifying complex topics related to fitness, health, and lifestyle. My experience ranges from working with elite athletes to everyday individuals striving for better health.

    My approach involves breaking down intricate concepts into digestible pieces, allowing people to grasp even the most challenging subjects logically. Whether it's discussing biomechanics, macronutrient metabolism, or sleep hygiene, I craft engaging and informative content that resonates with a wide audience.
    
    Furthermore, my expertise extends to copywriting, where I excel in creating compelling content that drives engagement and resonates with readers. From persuasive product descriptions to captivating blog posts, I deliver professional and impactful copy.
    
    Given a specific topic, I can generate a singular string response—an article title—that encapsulates the essence of the subject matter. Provide me with a topic, and I'll craft a title that captures its significance and draws readers in with clarity and intrigue.`


    const defaultSystemPrompt = `As an NSCA CSCS with a background in kinesiology, exercise science, and human nutrition, as well as experience working with elite athletes and everyday individuals striving for better health, I possess a unique skill set. I excel in explaining complex topics in simple, understandable ways, making me an effective communicator and educator in the realms of fitness, health, and lifestyle.

    My approach involves breaking down intricate concepts into digestible pieces, allowing people to grasp even the most challenging subjects logically. Whether it's discussing the biomechanics of a squat, the intricacies of macronutrient metabolism, or the importance of sleep hygiene, I have a knack for crafting engaging and informative content that resonates with a wide audience.
    
    Furthermore, my expertise extends to copywriting, where I specialize in creating compelling copy that drives engagement and resonates with readers. Whether it's crafting persuasive product descriptions, captivating blog posts, or informative articles, I have the skills to deliver professional and impactful content.
    
    With my background and proficiency in simplifying complex topics, I am well-equipped to contribute valuable insights and content to your application aimed at generating fitness, health, and lifestyle articles. By leveraging my expertise, your application can effectively educate and empower individuals to make informed decisions about their well-being.
    
    Input an article title, and I will generate a minimum of a 5 paragraph article going in-depth on the specified topic, drawing on my expertise and experience in the field of fitness, health, and lifestyle to elaborate and explain details of the topic. I will elaborate on the various subtopics that may be related to the article topic`
    

    const redditNSFWPostTitles = [
        "Can I handle all of this?",
        "Do you think I can handle it?",
        "Where would you put your hands on me?",
        "Can you handle my curves?",
        "Do you dare to explore with me?",
        "Can you resist the temptation?",
        "What would you do if I were yours?",
        "Can you handle my wild side?",
        "Do you want to play a little game?",
        "Where would you take me tonight?",
        "Do you think you can handle my intensity?",
        "Can you resist my allure?",
        "Where would you kiss me first?",
        "Can you handle my level of passion?",
        "What would you do if I asked you to?",
        "Do you think you can keep up with me?",
        "Can you handle the heat?",
        "What would you do to make me yours?",
        "Do you crave my touch?",
        "Can you handle the intensity of my gaze?",
        "Where would you like to get lost with me?",
        "Can you resist my seductive charm?",
        "What would you do if I whispered in your ear?",
        "Do you think you can handle my desires?",
        "Can you handle the thrill of the chase?",
        "What would you do if I gave you a chance?",
        "Do you dare to explore my fantasies?",
        "Can you handle my level of excitement?",
        "Where would you let me take the lead?",
        "Can you resist the urge to touch me?",
        "What would you do if I got closer?",
        "Do you think you can handle my passion?",
        "Can you handle the fire in my eyes?",
        "Where would you let me take you?",
        "Can you resist the temptation of my lips?",
        "What would you do if I asked for more?",
        "Do you dare to tease me back?",
        "Can you handle the intensity of my desire?",
        "Where would you let me explore?",
        "Can you resist the urge to hold me tight?",
        "What would you do if I gave you everything?",
        "Do you think you can handle my fantasies?",
        "Can you handle the thrill of the unknown?",
        "Where would you let me take control?",
        "Can you resist the urge to get closer?",
        "What would you do if I let you in?",
        "Do you dare to explore my secret desires?",
        "Can you handle the intensity of my touch?",
        "Where would you let me show you pleasure?",
    ]

    const redditSFWPostTitles = [
        "Am I cute enough to steal your heart?",
        "Do I look good in this outfit?",
        "Am I hot or just warm?",
        "Can you handle this level of cuteness?",
        "Do I make your heart skip a beat?",
        "Am I the definition of adorable?",
        "Does this smile brighten your day?",
        "Am I the missing piece to your puzzle?",
        "Can you resist this charm?",
        "Do you think I'm irresistible?",
        "Am I the sweetest temptation?",
        "Is this selfie worth a double-tap?",
        "Do I make your heart flutter?",
        "Am I your definition of beauty?",
        "Could I be your dream come true?",
        "Do I make this look effortless?",
        "Am I too cute to handle?",
        "Do you see the sparkle in my eyes?",
        "Can you handle my level of sass?",
        "Do I look like trouble?",
        "Am I selfie royalty?",
        "Is this the cutest selfie you've seen today?",
        "Can you resist swiping right?",
        "Do I light up your screen?",
        "Am I selfie perfection?",
        "Is this selfie worthy of your attention?",
        "Do I radiate positive vibes?",
        "Am I your selfie inspiration?",
        "Do I have that selfie game on point?",
        "Is this selfie making you smile?",
        "Am I selfie-ready?",
        "Do I look like a million bucks?",
        "Am I selfie royalty?",
        "Can you handle this level of fabulous?",
        "Do I make you stop scrolling?",
        "Am I your selfie soulmate?",
        "Do I look like a work of art?",
        "Am I selfie goals?",
        "Can you handle this level of fabulous?",
        "Do I have that selfie factor?",
        "Am I your selfie dream come true?",
        "Do I have that wow factor?",
        "Am I selfie-perfect?",
        "Can you handle this level of adorable?",
        "Do I make your heart skip a beat?",
        "Am I selfie-ready?",
        "Do I make your day brighter?",
        "Am I selfie royalty?",
        "Can you handle this level of cuteness?",
        "Do I make you smile?",
    ]

    module.exports = {
        topicArray,
        systemPromptForGettingTitle,
        defaultSystemPrompt,
        redditNSFWPostTitles,
        redditSFWPostTitles
    }