name: Deploy to linux

on: push

jobs:
  build:
    name: Build
    runs-on: self-hosted
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Add SSH key
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > key
        chmod 600 key
        eval $(ssh-agent)
        ssh-add key
    
    - name: Executing remote SSH commands using SSH key
      run: |
        ssh -o StrictHostKeyChecking=no gavin@192.168.1.121 << 'EOF'
          cd ./Desktop/open/openPost/
          echo "in directory, killing any running processes..."
          pkill -f node || echo "No Running Processes"
          echo "Pulling newest code..."
          git pull
          echo "installing..."
          npm install
        EOF

    - name: Kill existing ngrok session
      run: |
        ssh -o StrictHostKeyChecking=no gavin@192.168.1.121 << 'EOF'
          echo "Killing any running ngrok sessions..."
          pkill -f ngrok || echo "No Running ngrok Processes"
        EOF

    - name: Start ngrok
      run: |
        ssh -o StrictHostKeyChecking=no gavin@192.168.1.121 << 'EOF'
          cd ./Desktop/open/openPost/
          nohup ngrok http 3455 --domain moral-kindly-fly.ngrok-free.app &
        EOF

    - name: Start refreshCreds job in background
      run: |
        ssh -o StrictHostKeyChecking=no gavin@192.168.1.121 << 'EOF'
          cd ./Desktop/open/openPost/
          echo "starting refresh creds job in background"
          nohup npm run refreshCreds > refreshCreds.log 2>&1 &
        EOF

    - name: Start api
      run: |
        ssh -o StrictHostKeyChecking=no gavin@192.168.1.121 << 'EOF'
          cd ./Desktop/open/openPost/
          echo "starting api in background"
          nohup npm start > openPostApi.log 2>&1 &
        EOF

    - name: Start client
      run: |
        ssh -o StrictHostKeyChecking=no gavin@192.168.1.121 << 'EOF'
          cd ./Desktop/open/openPost/
          echo "starting client in background"
          nohup npm run client > openPostClient.log 2>&1 &
        EOF
